import { Inter, UnifrakturMaguntia } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const unifrakturMaguntia = UnifrakturMaguntia({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-unifrak",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${unifrakturMaguntia.variable}`}>
        {children}
      </body>
    </html>
  );
}
